### ISSUE TITLE
[Crash] Game crashes just after loading.

### ISSUE THREAD

**Issue by legoisland21** [MeteorClientPlus/MeteorPlus#14]
### Describe the bug

So, normally Meteor loads but with the mod it crashes, doesnt even load the menu just straight up crashes.

Mod list:
appleskin-fabric-mc1.21-3.0.6
baritone-standalone-fabric-1.10.2-9-g3b01f129
betterhurtcam-1.9.1+mc1.21
BetterPvP_24.7.1_Fabric_1.21
fabric-api-0.105.0+1.21.1
Fabric-Language-Kotlin-Mod-1.21
jei-1.21.1-fabric-19.21.0.247
meteor-client-0.5.8
modernfix-fabric-5.19.6+mc1.21.1
preview_OptiFine_1.21.4_HD_U_J3_pre4
ukulib-1.3.0+1.21

### Steps to reproduce

```bash
1. Put Meteor+ in the mods folder.
2. Start up the game.
3. And it crashes.
```

### Meteor Plus Version

Both 1.0.9.0 and 1.0.8.9.

### Minecraft Version

1.21.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.

- [X] This is a valid bug.

**Comment by Nekiplay** [comment]
install fabric api

**Comment by Nekiplay** [comment]
send crash log

**Comment by legoisland21** [comment]
i am not sure if im sending the right stuff but i got it from the logs folder:

[08:20:42] [main/INFO]: Loading Minecraft 1.21.1 with Fabric Loader 0.16.9
[08:20:42] [ForkJoinPool-1-worker-12/WARN]: Mod meteorplus uses the version 1.21.1_1.0.9.2 which isn't compatible with Loader's extended semantic version format (Could not parse version number component '1_1'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[08:20:42] [main/INFO]: Loading 82 mods:
	- appleskin 3.0.6+mc1.21
	   \-- cloth-config 15.0.127
	        \-- cloth-basic-math 0.6.1
	- baritone 1.10.2-9-g3b01f129
	   \-- dev_babbaj_nether-pathfinder 1.4.1
	- betterhurtcam 1.9.1+mc1.21
	   \-- fabric-key-binding-api-v1 1.0.47+0af3f5a790
	- fabric-api 0.105.0+1.21.1
	   |-- fabric-api-base 0.4.42+6573ed8c19
	   |-- fabric-api-lookup-api-v1 1.6.68+b559734419
	   |-- fabric-biome-api-v1 13.0.29+5bd9f1bc19
	   |-- fabric-block-api-v1 1.0.22+0af3f5a719
	   |-- fabric-block-view-api-v2 1.0.10+6573ed8c19
	   |-- fabric-blockrenderlayer-v1 1.1.52+0af3f5a719
	   |-- fabric-client-tags-api-v1 1.1.15+6573ed8c19
	   |-- fabric-command-api-v1 1.2.49+f71b366f19
	   |-- fabric-command-api-v2 2.2.28+6ced4dd919
	   |-- fabric-commands-v0 0.2.66+df3654b319
	   |-- fabric-content-registries-v0 8.0.16+b559734419
	   |-- fabric-convention-tags-v1 2.0.23+7f945d5b19
	   |-- fabric-convention-tags-v2 2.8.0+9d22c5fd19
	   |-- fabric-crash-report-info-v1 0.2.29+0af3f5a719
	   |-- fabric-data-attachment-api-v1 1.1.28+1daea21519
	   |-- fabric-data-generation-api-v1 20.2.20+16c4ae2519
	   |-- fabric-dimensions-v1 4.0.0+6fc22b9919
	   |-- fabric-entity-events-v1 1.7.0+2122d82819
	   |-- fabric-events-interaction-v0 0.7.13+ba9dae0619
	   |-- fabric-game-rule-api-v1 1.0.53+6ced4dd919
	   |-- fabric-item-api-v1 11.1.0+d5debaed19
	   |-- fabric-item-group-api-v1 4.1.5+3fc0e55219
	   |-- fabric-keybindings-v0 0.2.45+df3654b319
	   |-- fabric-lifecycle-events-v1 2.3.12+6c1df36019
	   |-- fabric-loot-api-v2 3.0.14+3f89f5a519
	   |-- fabric-loot-api-v3 1.0.2+3f89f5a519
	   |-- fabric-message-api-v1 6.0.13+6573ed8c19
	   |-- fabric-model-loading-api-v1 2.0.0+fe474d6b19
	   |-- fabric-networking-api-v1 4.3.0+c7469b2119
	   |-- fabric-object-builder-api-v1 15.2.0+40875a9319
	   |-- fabric-particles-v1 4.0.2+6573ed8c19
	   |-- fabric-recipe-api-v1 5.0.13+6508971219
	   |-- fabric-registry-sync-v0 5.1.3+60c3209b19
	   |-- fabric-renderer-api-v1 3.4.0+c705a49c19
	   |-- fabric-renderer-indigo 1.7.0+c705a49c19
	   |-- fabric-renderer-registries-v1 3.2.68+df3654b319
	   |-- fabric-rendering-data-attachment-v1 0.3.48+73761d2e19
	   |-- fabric-rendering-fluids-v1 3.1.6+1daea21519
	   |-- fabric-rendering-v0 1.1.71+df3654b319
	   |-- fabric-rendering-v1 5.0.5+df16efd019
	   |-- fabric-resource-conditions-api-v1 4.3.0+8dc279b119
	   |-- fabric-resource-loader-v0 1.3.0+5659912919
	   |-- fabric-screen-api-v1 2.0.25+8b68f1c719
	   |-- fabric-screen-handler-api-v1 1.3.87+b559734419
	   |-- fabric-sound-api-v1 1.0.23+6573ed8c19
	   |-- fabric-transfer-api-v1 5.3.0+d831205f19
	   \-- fabric-transitive-access-wideners-v1 6.1.0+1daea21519
	- fabric-language-kotlin 1.11.0+kotlin.2.0.0
	   |-- org_jetbrains_kotlin_kotlin-reflect 2.0.0
	   |-- org_jetbrains_kotlin_kotlin-stdlib 2.0.0
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 2.0.0
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 2.0.0
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.24.0
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.8.1
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.8.1
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.6.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.6.3
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.6.3
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.6.3
	- fabricloader 0.16.9
	   \-- mixinextras 0.4.1
	- gurkensgadgetry 1.4.0
	- java 21
	- jei 19.21.0.247
	- meteor-client 0.5.8
	- meteorist 1.10
	- meteorplus 1.21.1_1.0.9.2
	   \-- mixinextras 0.4.1
	- minecraft 1.21.1
	- modernfix 5.19.6+mc1.21.1
	- streak-addon 1.2.7
	- ukulib 1.3.0+1.21
	   \-- com_moandjiezana_toml_toml4j 0.7.2
	- xaerobetterpvp 24.7.1
	- zewo2 1.1.0
[08:20:42] [main/WARN]: Found 1 non-fabric mod:
	- preview_OptiFine_1.21.4_HD_U_J3_pre4.jar
[08:20:43] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.7 Source=file:/C:/Users/wrzoc/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.15.4+mixin.0.8.7/sponge-mixin-0.15.4+mixin.0.8.7.jar Service=Knot/Fabric Env=CLIENT
[08:20:43] [main/INFO]: Compatibility level set to JAVA_21
[08:20:43] [main/INFO]: Loaded configuration file for ModernFix 5.19.6+mc1.21.1: 54 options available, 0 override(s) found
[08:20:43] [main/INFO]: Applying Nashorn fix
[08:20:43] [main/WARN]: Error loading class: baritone/command/defaults/ComeCommand (java.lang.ClassNotFoundException: baritone/command/defaults/ComeCommand)
[08:20:43] [main/WARN]: @Mixin target baritone.command.defaults.ComeCommand was not found meteor-client-baritone.mixins.json:ComeCommandMixin from mod meteor-client
[08:20:44] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.4.1).
[08:20:47] [Datafixer Bootstrap/INFO]: 226 Datafixer optimizations took 1501 milliseconds
[08:20:48] [main/WARN]: @Final field sgTargeting:Lmeteordevelopment/meteorclient/settings/SettingGroup; in meteorplus.mixins.json:meteorclient.modules.KillAuraMixin from mod meteorplus should be final
[08:20:48] [main/WARN]: @Final field sgTiming:Lmeteordevelopment/meteorclient/settings/SettingGroup; in meteorplus.mixins.json:meteorclient.modules.KillAuraMixin from mod meteorplus should be final
[08:20:48] [main/WARN]: @Final field entities:Lmeteordevelopment/meteorclient/settings/Setting; in meteorplus.mixins.json:meteorclient.modules.KillAuraMixin from mod meteorplus should be final
[08:20:48] [main/WARN]: @Final field targets:Ljava/util/List; in meteorplus.mixins.json:meteorclient.modules.KillAuraMixin from mod meteorplus should be final
[08:20:48] [main/WARN]: @Final field customDelay:Lmeteordevelopment/meteorclient/settings/Setting; in meteorplus.mixins.json:meteorclient.modules.KillAuraMixin from mod meteorplus should be final
[08:20:48] [main/WARN]: @Final field sgGeneral:Lmeteordevelopment/meteorclient/settings/SettingGroup; in meteorplus.mixins.json:meteorclient.modules.AutoToolMixin from mod meteorplus should be final
[08:20:48] [main/WARN]: @Final field prefer:Lmeteordevelopment/meteorclient/settings/Setting; in meteorplus.mixins.json:meteorclient.modules.AutoToolMixin from mod meteorplus should be final
[08:20:48] [main/WARN]: @Final field silkTouchForEnderChest:Lmeteordevelopment/meteorclient/settings/Setting; in meteorplus.mixins.json:meteorclient.modules.AutoToolMixin from mod meteorplus should be final
[08:20:48] [main/WARN]: @Final field fortuneForOresCrops:Lmeteordevelopment/meteorclient/settings/Setting; in meteorplus.mixins.json:meteorclient.modules.AutoToolMixin from mod meteorplus should be final
[08:20:48] [main/WARN]: @Final field antiBreak:Lmeteordevelopment/meteorclient/settings/Setting; in meteorplus.mixins.json:meteorclient.modules.AutoToolMixin from mod meteorplus should be final
[08:20:48] [main/WARN]: @Final field breakDurability:Lmeteordevelopment/meteorclient/settings/Setting; in meteorplus.mixins.json:meteorclient.modules.AutoToolMixin from mod meteorplus should be final
[08:20:48] [main/WARN]: @Final field switchDelay:Lmeteordevelopment/meteorclient/settings/Setting; in meteorplus.mixins.json:meteorclient.modules.AutoToolMixin from mod meteorplus should be final
[08:20:48] [main/WARN]: @Final field sgWhitelist:Lmeteordevelopment/meteorclient/settings/SettingGroup; in meteorplus.mixins.json:meteorclient.modules.AutoToolMixin from mod meteorplus should be final
[08:20:48] [main/WARN]: @Final field listMode:Lmeteordevelopment/meteorclient/settings/Setting; in meteorplus.mixins.json:meteorclient.modules.AutoToolMixin from mod meteorplus should be final
[08:20:48] [main/WARN]: @Final field whitelist:Lmeteordevelopment/meteorclient/settings/Setting; in meteorplus.mixins.json:meteorclient.modules.AutoToolMixin from mod meteorplus should be final
[08:20:48] [main/WARN]: @Final field blacklist:Lmeteordevelopment/meteorclient/settings/Setting; in meteorplus.mixins.json:meteorclient.modules.AutoToolMixin from mod meteorplus should be final
[08:20:48] [main/WARN]: @Final field sgGeneral:Lmeteordevelopment/meteorclient/settings/SettingGroup; in meteorplus.mixins.json:meteorclient.modules.MiddleClickExtraMixin from mod meteorplus should be final
[08:20:48] [main/WARN]: Discarding @Unique public field packetMine in meteorplus.mixins.json:meteorclient.modules.BreakIndicatorsMixin from mod meteorplus because it already exists in meteordevelopment.meteorclient.systems.modules.render.BreakIndicators. Note that declared FIELD INITIALISERS will NOT be removed!
[08:20:49] [main/WARN]: Error loading class: baritone/api/pathing/goals/GoalBlock (java.lang.ClassNotFoundException: baritone/api/pathing/goals/GoalBlock)
[08:20:50] [main/WARN]: Failed to get system info for GL Caps
java.lang.IllegalStateException: Rendersystem called from wrong thread
	at knot/com.mojang.blaze3d.systems.RenderSystem.constructThreadException(RenderSystem.java:140) ~[client-intermediary.jar:?]
	at knot/com.mojang.blaze3d.systems.RenderSystem.assertOnRenderThread(RenderSystem.java:135) ~[client-intermediary.jar:?]
	at knot/com.mojang.blaze3d.systems.RenderSystem.getCapsString(RenderSystem.java:527) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_6396.method_37123(class_6396.java:70) [client-intermediary.jar:?]
	at knot/net.minecraft.class_310.method_37274(class_310.java:2547) [client-intermediary.jar:?]
	at knot/net.minecraft.class_310.method_22681(class_310.java:2517) [client-intermediary.jar:?]
	at knot/net.minecraft.client.main.Main.main(Main.java:210) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.9.jar:?]
[08:20:50] [main/WARN]: Error loading class: baritone/api/pathing/goals/GoalBlock (java.lang.ClassNotFoundException: baritone/api/pathing/goals/GoalBlock)
[08:20:50] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Mixin transformation of meteordevelopment.meteorclient.systems.modules.render.Freecam failed
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:482) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.9.jar:?]
Caused by: java.lang.RuntimeException: Mixin transformation of meteordevelopment.meteorclient.systems.modules.render.Freecam failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.9.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	at knot/net.minecraft.class_128.handler$bbk000$meteor-client$onAddDetails(class_128.java:533) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_128.method_555(class_128.java:81) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_128.method_60921(class_128.java:132) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_128.method_60920(class_128.java:138) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_310.method_1565(class_310.java:959) ~[client-intermediary.jar:?]
	at knot/net.minecraft.client.main.Main.main(Main.java:211) ~[fabric-loader-0.16.9-1.21.1.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) ~[fabric-loader-0.16.9.jar:?]
	... 2 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at knot/meteordevelopment.meteorclient.asm.Asm$Transformer.transformClassBytes(Asm.java:104) ~[meteor-client-0.5.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.9.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	at knot/net.minecraft.class_128.handler$bbk000$meteor-client$onAddDetails(class_128.java:533) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_128.method_555(class_128.java:81) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_128.method_60921(class_128.java:132) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_128.method_60920(class_128.java:138) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_310.method_1565(class_310.java:959) ~[client-intermediary.jar:?]
	at knot/net.minecraft.client.main.Main.main(Main.java:211) ~[fabric-loader-0.16.9-1.21.1.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) ~[fabric-loader-0.16.9.jar:?]
	... 2 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinPreProcessorException: Attach error for meteorplus.mixins.json:meteorclient.modules.FreecamMixin from mod meteorplus during activity: [Transform -> Method Work(Lmeteordevelopment/meteorclient/events/Cancellable;)V -> INVOKESPECIAL -> baritone/api/pathing/goals/GoalBlock::<init>:(Lnet/minecraft/class_2338;)V]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:313) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1292) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:203) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:437) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:418) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at knot/meteordevelopment.meteorclient.asm.Asm$Transformer.transformClassBytes(Asm.java:104) ~[meteor-client-0.5.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.9.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	at knot/net.minecraft.class_128.handler$bbk000$meteor-client$onAddDetails(class_128.java:533) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_128.method_555(class_128.java:81) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_128.method_60921(class_128.java:132) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_128.method_60920(class_128.java:138) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_310.method_1565(class_310.java:959) ~[client-intermediary.jar:?]
	at knot/net.minecraft.client.main.Main.main(Main.java:211) ~[fabric-loader-0.16.9-1.21.1.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) ~[fabric-loader-0.16.9.jar:?]
	... 2 more
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: baritone.api.pathing.goals.GoalBlock
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformMemberReference(MixinPreProcessorStandard.java:791) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformMethod(MixinPreProcessorStandard.java:777) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transform(MixinPreProcessorStandard.java:743) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:307) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1292) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:203) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:437) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:418) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at knot/meteordevelopment.meteorclient.asm.Asm$Transformer.transformClassBytes(Asm.java:104) ~[meteor-client-0.5.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.9.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	at knot/net.minecraft.class_128.handler$bbk000$meteor-client$onAddDetails(class_128.java:533) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_128.method_555(class_128.java:81) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_128.method_60921(class_128.java:132) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_128.method_60920(class_128.java:138) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_310.method_1565(class_310.java:959) ~[client-intermediary.jar:?]
	at knot/net.minecraft.client.main.Main.main(Main.java:211) ~[fabric-loader-0.16.9-1.21.1.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) ~[fabric-loader-0.16.9.jar:?]
	... 2 more
Caused by: java.lang.ClassNotFoundException: baritone.api.pathing.goals.GoalBlock
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformMemberReference(MixinPreProcessorStandard.java:791) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformMethod(MixinPreProcessorStandard.java:777) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transform(MixinPreProcessorStandard.java:743) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:307) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1292) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:203) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:437) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:418) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at knot/meteordevelopment.meteorclient.asm.Asm$Transformer.transformClassBytes(Asm.java:104) ~[meteor-client-0.5.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.9.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	at knot/net.minecraft.class_128.handler$bbk000$meteor-client$onAddDetails(class_128.java:533) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_128.method_555(class_128.java:81) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_128.method_60921(class_128.java:132) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_128.method_60920(class_128.java:138) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_310.method_1565(class_310.java:959) ~[client-intermediary.jar:?]
	at knot/net.minecraft.client.main.Main.main(Main.java:211) ~[fabric-loader-0.16.9-1.21.1.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) ~[fabric-loader-0.16.9.jar:?]
	... 2 more

**Comment by Nekiplay** [comment]
Install baritone-api-fabric, not baritone-standalone-fabric

**Comment by legoisland21** [comment]
thanks! it works perfectly fine now.
